### ISSUE TITLE
syntax highlight on github

### ISSUE THREAD

**Issue by gares** [sacerdot/Minimalist-Type-Theory-In-Lambda-Prolog#7]
I suggest adding a `.gitattribute` file as in https://github.com/LPCIC/coq-elpi/blob/master/.gitattributes
This way you get some colors. Example: https://github.com/LPCIC/coq-elpi/blob/master/coq-lib.elpi

Note: a file gets the new syntax highlighting active only after a change, just adding the `.gitattributes` is not enough.

**Comment by fifofefe** [comment]
Thanks, I made the changes :) now it is a lot better
